In [1]:
import sys, os
sys.path.append(os.path.abspath(".."))
import numpy as np
from spaces.SPD import SymmetricPositiveDefinite
from algorithms.ProxSpliting import Prox

In [2]:
spd = SymmetricPositiveDefinite(dimension=3, metric= "airm") 
S = spd.sample(n_samples=10, seed=0, dtype=np.float64)

prox = Prox(space=spd)
prox.prox_mapping_dist(S[0], S[1], lam=0.5)

array([[ 0.09414748, -0.25182695,  0.15731341],
       [-0.25182695,  1.45275064,  0.06745543],
       [ 0.15731341,  0.06745543,  1.08021017]])

In [3]:
prox.cyclic(S[0], S, lam=0.5)

/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate, approximate err = 4.877320257624895e-13
  logX = logm(X)
/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate, approximate err = 2.9751229716764475e-13
  logX = logm(X)
/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate, approximate err = 6.139842660163829e-13
  logX = logm(X)


array([[ 0.09282927, -0.11934337,  0.10018706],
       [-0.11934337,  0.65709876, -0.49163306],
       [ 0.10018706, -0.49163306,  1.60438297]])

In [4]:
prox.relaxed_cyclic(S[0], S, lam=0.5)

array([[ 0.06395458, -0.04490894,  0.05121428],
       [-0.04490894,  0.56913247, -0.18904852],
       [ 0.05121428, -0.18904852,  1.34349683]])

In [6]:
fm, seq = prox.Frechet_mean(S[0], S, method = "relaxed", 
                            tau=0.5, 
                            lam=0.5,  
                            p=2.0,
                            tol=1e-16, max_outer_iter=200)


  0%|          | 0/200 [00:00<?, ?it/s]/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate, approximate err = 3.816849910582295e-13
  logX = logm(X)
/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate, approximate err = 3.984007051857137e-13
  logX = logm(X)
/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate, approximate err = 6.308412339476408e-13
  logX = logm(X)
/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate, approximate err = 3.466962714569206e-13
  logX = logm(X)
/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate, approximate err = 3.676279661679648e-13
  logX = logm(X)
/Users/mahshid/Documents/Research/code/ProxOpt/spaces/SPD.py:108: RuntimeWarning: logm result may be inaccurate

In [7]:
fm

array([[ 0.07133933, -0.04698486,  0.03810743],
       [-0.04698486,  0.54690284, -0.31883124],
       [ 0.03810743, -0.31883124,  1.39124179]])