In [1]:
import sys, os
sys.path.append(os.path.abspath(".."))
import numpy as np
from spaces.sphere import Sphere

In [2]:
space = Sphere(dimension=3) 
S = space.sample(n_samples=10, seed=0, dtype=np.float64)  # shape (n, dim, dim)
np.set_printoptions(precision=20, suppress=False)      # print decimals with controlled precision
print(S.shape)
print(S) 

(10, 3)
[[ 0.18881711923692265  -0.19839032737660414   0.9617636786063786  ]
 [ 0.16021416297716448  -0.818128926665578     0.5522648652001644  ]
 [ 0.7415052042025201    0.5385471155343273   -0.4001712589507583  ]
 [-0.8967022761251738   -0.4416644114201207    0.029284393059288184]
 [-0.8784069177470692   -0.08266045905288898  -0.4707106705432322  ]
 [-0.7583158229918717   -0.5636195521419911   -0.32755169522293953 ]
 [ 0.3648617673568587    0.9240647543268903   -0.11393077078653183 ]
 [ 0.8759982916180951   -0.4264361324882868    0.22534244604736822 ]
 [ 0.7696741376445092    0.0800898974604638   -0.6333935034131261  ]
 [-0.8758196390296379   -0.43492918578181555   0.20922849529918608 ]]


In [3]:
space.set_metric("Spherical")
d = [space.dist(S[i],S[i+1]) for i in range(len(S)-1)]
d

[0.7616354712663141,
 2.1445659592454667,
 2.7250302826248256,
 0.6259734213403944,
 0.521885051421135,
 2.4343913635928836,
 1.6710740551785817,
 1.0502553188393726,
 2.5707632797345408]

In [4]:
space.set_metric("Euclidean")
d = [space.dist(S[i],S[i+1]) for i in range(len(S)-1)]
d

[0.7433594949528488,
 1.7565886623440587,
 1.956775547480946,
 0.6158032328433858,
 0.5159825699375412,
 1.8762639458595487,
 1.4833136914972709,
 1.0026469346832203,
 1.9190899556537204]

In [5]:
space.convex_combination(S[0], S[1], t=0.2)

array([ 0.19177020256666352, -0.3376078907304967 ,  0.9215449536099939 ])

In [7]:
space.set_metric("Spherical")
space.convex_combination(S[0], S[1], t=0.2)

array([ 0.19181228989528942, -0.34441186067807567,  0.9190149703184336 ])